Catkin-ProjectName: object_recognition_linemod
Version: 0.1.1
Description: An object recognition pipeline that uses LINE-MOD from OpenCV

Author: Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  https://github.com/wg-perception/linemod

Depends: catkin, ecto, object_recognition_core, opencv2

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
